# Based on https://github.com/mkdocs-material/create-blog/blob/main/mkdocs.yml
# and on https://github.com/antocuni/antocuni.github.io/tree/main

site_name: Blog of cast42
site_description: Blog of cast42
site_url: https://cast42.github.io/blog/
docs_dir: blog

nav:
  - About: about.md
  - Tags: tags.md
  - RSS feed: feed_rss_updated.xml

theme:
  logo: assets/logo.svg
  favicon: assets/logo.svg
  name: material
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.suggest
    - header.autohide

plugins:
  - blog:
      blog_dir: .
      post_excerpt: required
      pagination: true
      post_url_format: "{date}/{slug}"
      post_date_format: medium
      categories: true

      draft: true # include drafts

  - search
  - tags
  - glightbox:
      auto_caption: true

  - rss:
      match_path: "posts/.*"
      comments_path: "#__comments"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated


# https://squidfunk.github.io/mkdocs-material/setup/extensions/
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg



