[project]
name = "blog"
version = "0"
description = "Blog of cast42"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "mkdocs>=1.6.1",
    "fastapi", 
    "granian",
    "stamina"
]

[dependency-groups]
dev = ["fastapi[standard]", "pytest"]
